hydra:
  run:
    dir: ./outputs/ver_1.0/logs

main:
  version: not_selected # format: ver_4.1, ver_4.2 ... Note, make sure matching with processing module name for preventing confusion.
  process_type: instruction # Select one [preference, insturction]
  sample_size: not_selected
  valid_size: 1000

defaults:
  - instruction: ver_1.1.yaml
  - preference: ver_1.0.yaml

dataset_path: /Users/nam-young-woo/Desktop/codes/llm_data_processing/datas/
use_system: True