hydra:
  run:
    dir: ./outputs/ver_1.0/logs

main:
  version: not_selected # format: ver_4.1, ver_4.2 ... Note, make sure matching with processing module name for preventing confusion.
  process_type: instruction # Select one [dpo, insturction]
  sample_size: not_selected
  valid_size: 1000

defaults:
  - instruction: ver_1.0.yaml

dataset_path: ~/Desktop/codes/llm_data_processing/datas/